ElijahEsparzaa/491-Project

.github/workflows/main.yaml

All the tools we will be using for CI/CD on this Github Action YAML

Created main.yaml CI/CD

---

Assets/Scripts/Player/PlayerMovement.cs
Assets/Scripts/Player/PlayerMovement.cs.meta

Script for Player movement in unity

Player Movement script

---

Assets/Scripts/Player/CharacterScriptableObjects.cs
Assets/Scripts/Player/CharacterScriptableObjects.cs.meta

Script for Character selection prefabs (2 character options) sword thrower character and shield character and applies the prefab to player.

Character Scriptable Objects

---

Assets/Scripts/Player/InventoryManager.cs
Assets/Scripts/Player/InventoryManager.cs.meta

Script for player inventory system in game that keeps track of items and weapons the player currently has in game.

Inventory Manager Script

---

Assets/Scripts/Player/PlayerCollector.cs
Assets/Scripts/Player/PlayerCollector.cs.meta

Script that allows the player to "collect" items and update its player stats such as health when a health potion is collected and player xp when an xp potion is collected.

Player Collector Script

---

Assets/Scripts/Interfaces/Item Collector.cs
Assets/Scripts/Interfaces/Item Collector.cs.meta

Script for item collection in game

Item Collector

---

Assets/Scripts/Player/PlayerStats.cs
Assets/Scripts/Player/PlayerStats.cs.meta

Script that gives the player in game stats such as health, speed and attack stats

Player Stats script

---

Assets/Scripts/Map/ChunkTrigger.cs
Assets/Scripts/Map/ChunkTrigger.cs.meta
Assets/Scripts/Map/MapController.cs
Assets/Scripts/Map/MapController.cs.meta
Assets/Scripts/Map/PropRandomizer.cs
Assets/Scripts/Map/PropRandomizer.cs.meta

The scripts allow the prefabbed tilemaps to generate themselves and create an "infinite" map as the player moves around. This is a bundle of scripts.  Uses the tilemap Prefabs.

Tilemap inital Gen

---

Assets/Scripts/BreakableProps.cs
Assets/Scripts/BreakableProps.cs.meta

Objects in game should be breakable if hit with any sort of damage. Different props can be added, it just needs to be done using different prefabs.

Breakable Props

---

Assets/Scripts/Player/CameraMovement.cs
Assets/Scripts/Player/CameraMovement.cs.meta

Script for Camera movement so that it follows the player and keeps the player in the center of the screen as they move.

Camera Movement Script

---

Assets/Scripts/Weapons/Weapon Base/WeaponController.cs
Assets/Scripts/Weapons/Weapon Base/WeaponController.cs.meta

Script that controls the in game weapons, as well as when characters are picked it gives them their corresponding starter weapon.

Weapon Controller

---

Assets/Scripts/Weapons/Weapon Base/ProjectileWeapon.cs
Assets/Scripts/Weapons/Weapon Base/ProjectileWeapon.cs.meta

Script for the Projectile Weapon in game. (Thrown knife, the actually throwing mechanic).

Projectile Weapon

---

Assets/Scripts/Weapons/Weapon Base/MeleeWeaponBehaviour.cs
Assets/Scripts/Weapons/Weapon Base/MeleeWeaponBehaviour.cs.meta

Script for in game weapon behavior.

Melee Weapon Behavior

---

Assets/Scripts/Weapons/Weapon Controllers/KnifeController.cs
Assets/Scripts/Weapons/Weapon Controllers/KnifeController.cs.meta

Script for Knife controller that spawns the thrown knife attack

Knife Controller

---

Assets/Scripts/Weapons/Weapon Controllers/ShieldController.cs
Assets/Scripts/Weapons/Weapon Controllers/ShieldController.cs.meta

Script for Shield Controller that spawns the shield weapon in game.

Shield Controller

---

Assets/Prefabs/Weapons/Controller.meta
Assets/Prefabs/Weapons/Controller/Knife Weapon.meta
Assets/Prefabs/Weapons/Controller/Knife Weapon/Knife Controller Level 2.prefab
Assets/Prefabs/Weapons/Controller/Knife Weapon/Knife Controller Level 2.prefab.meta
Assets/Prefabs/Weapons/Controller/Knife Weapon/Knife Controller.prefab
Assets/Prefabs/Weapons/Controller/Knife Weapon/Knife Controller.prefab.meta
Assets/Prefabs/Weapons/Controller/Shield Weapon.meta
Assets/Prefabs/Weapons/Controller/Shield Weapon/Aoe Shield Controller Level 2.prefab
Assets/Prefabs/Weapons/Controller/Shield Weapon/Aoe Shield Controller Level 2.prefab.meta
Assets/Prefabs/Weapons/Controller/Shield Weapon/Aoe Shield Controller.prefab
Assets/Prefabs/Weapons/Controller/Shield Weapon/Aoe Shield Controller.prefab.meta
Assets/Prefabs/Weapons/Non-Controller.meta
Assets/Prefabs/Weapons/Non-Controller/Knife Weapon.meta
Assets/Prefabs/Weapons/Non-Controller/Knife Weapon/Throwable Knife Level 2.prefab
Assets/Prefabs/Weapons/Non-Controller/Knife Weapon/Throwable Knife Level 2.prefab.meta
Assets/Prefabs/Weapons/Non-Controller/Knife Weapon/Throwable Knife.prefab
Assets/Prefabs/Weapons/Non-Controller/Knife Weapon/Throwable Knife.prefab.meta
Assets/Prefabs/Weapons/Non-Controller/Shield Weapon.meta
Assets/Prefabs/Weapons/Non-Controller/Shield Weapon/Aoe Shield Level 2.prefab
Assets/Prefabs/Weapons/Non-Controller/Shield Weapon/Aoe Shield Level 2.prefab.meta
Assets/Prefabs/Weapons/Non-Controller/Shield Weapon/Aoe Shield.prefab
Assets/Prefabs/Weapons/Non-Controller/Shield Weapon/Aoe Shield.prefab.meta

Prefabs for all weapons in game

Weapons Prefabs

---

Assets/Prefabs/Pick-ups/Health Potion.prefab
Assets/Prefabs/Pick-ups/Health Potion.prefab.meta
Assets/Prefabs/Pick-ups/XP Potion.prefab
Assets/Prefabs/Pick-ups/XP Potion.prefab.meta

Pick Items Prefabs

---

Assets/Prefabs/Passive Items/Spinach Passive Item.meta
Assets/Prefabs/Passive Items/Spinach Passive Item/Spinach Level 2.prefab
Assets/Prefabs/Passive Items/Spinach Passive Item/Spinach Level 2.prefab.meta
Assets/Prefabs/Passive Items/Spinach Passive Item/Spinach.prefab
Assets/Prefabs/Passive Items/Spinach Passive Item/Spinach.prefab.meta
Assets/Prefabs/Passive Items/Wings Passive Item.meta
Assets/Prefabs/Passive Items/Wings Passive Item/Wings Level 2.prefab
Assets/Prefabs/Passive Items/Wings Passive Item/Wings Level 2.prefab.meta
Assets/Prefabs/Passive Items/Wings Passive Item/Wings.prefab
Assets/Prefabs/Passive Items/Wings Passive Item/Wings.prefab.meta

Prefabs for all the Passive items and their Level Ups.

Passive Items Prefabs

---

Assets/Scripts/Passive Items/PassiveItem.cs
Assets/Scripts/Passive Items/PassiveItem.cs.meta
Assets/Scripts/Passive Items/PassiveItemScriptableObject.cs
Assets/Scripts/Passive Items/PassiveItemScriptableObject.cs.meta
Assets/Scripts/Passive Items/SpinachPassiveItem.cs
Assets/Scripts/Passive Items/SpinachPassiveItem.cs.meta
Assets/Scripts/Passive Items/WingsPassiveItem.cs
Assets/Scripts/Passive Items/WingsPassiveItem.cs.meta

Script for general passive items applying to the player, Script for passive items to make them scriptable objects in game, script for strength passive item that increases players strength stat, Script for speed passive item that increases players speed stat.

Passive Items Script

---

Assets/Scripts/SceneController.cs
Assets/Scripts/SceneController.cs.meta

Script for Scene changing via Scene Manager

Scene Controller

---

Assets/Scripts/GameManager.cs
Assets/Scripts/GameManager.cs.meta

Script for Game Scene transition.

Game Manager

---

Assets/Scripts/DropRateManager.cs
Assets/Scripts/DropRateManager.cs.meta

Script that applies item drop rate to the game.

Item Drop Rate Manager

---

Assets/Scenes/Game.unity
Assets/Scenes/Game.unity.meta
Assets/Scenes/Main Menu.unity
Assets/Scenes/Main Menu.unity.meta
Assets/Scenes/Pause Menu.unity
Assets/Scenes/Pause Menu.unity.meta

Merging created Game scene, main menu scene, pause menu scene.

In game Scenes
